spring.application.name=auth_service

logging.level.org.springframework.security=DEBUG

//jwt???
jwt.secret=my-secret-key-for-auth-service
//jwt????
jwt.expiration=3600000

# H2???????????????????????????????
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console??????????????????????????
spring.h2.console.enabled=true

# Hibernate?SQL??????????????????????
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update