spring.application.name=auth_service

logging.level.org.springframework.security=DEBUG

//jwt???
jwt.secret=my-secret-key-for-auth-service
//jwt????
jwt.expiration=3600000

# H2 Console??????????????????????????
#spring.h2.console.enabled=true

# ???? 5433 ???
spring.datasource.url=jdbc:postgresql://localhost:5433/authdb
spring.datasource.username=user
spring.datasource.password=pass
spring.jpa.hibernate.ddl-auto=update

# ?????SQL????????
spring.jpa.show-sql=true
# SQL??????????
spring.jpa.properties.hibernate.format_sql=true

# --- ????JPA?????????????? ---
# ???????????@Table(name="users")??????????????
#spring.jpa.hibernate.ddl-auto=update
# ?????SQL??????????????????
#spring.jpa.show-sql=true
# PostgreSQL????????????
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
